on:
  push:
    branches:
      - main
    paths:
      - 'keyring/scribblings/**'
      - '.github/workflows/docs.yml'
jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install racket
      uses: Bogdanp/setup-racket@v1.8.1
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: 'stable'
    - name: install base package
      run: raco pkg install --batch --auto ./keyring-lib ./keyring
    - name: build docs
      run: scribble +m --redirect-main http://pkg-build.racket-lang.org/doc/ --htmls --dest ./docs ./keyring/scribblings/keyring.scrbl
    - name: push to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        folder: docs/keyring
        branch: gh-pages
