on:
  push:
  pull_request:
  schedule:
  - cron: "17 16 * * FRI"
jobs:
  test:
    strategy:
      matrix:
        racket-variant: ["BC", "CS"]
        racket-version: ["8.8", "8.9", "pre-release", "stable", "current"]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install racket
      uses: Bogdanp/setup-racket@v1.8.1
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}
    - name: install base package
      run: raco pkg install --batch --auto ./keyring-lib ./keyring-test ./keyring
    - name: run base tests
      run: raco test --drdr --package keyring-test
